/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVerifier__factory } from "./IVerifier__factory";
export { Identify__factory } from "./Identify__factory";
