/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as identifySol from "./Identify.sol";
export type { identifySol };
import type * as verifierSol from "./Verifier.sol";
export type { verifierSol };
export * as factories from "./factories";
export type { Identify } from "./Identify.sol/Identify";
export { Identify__factory } from "./factories/Identify.sol/Identify__factory";
export type { IVerifier } from "./Identify.sol/IVerifier";
export { IVerifier__factory } from "./factories/Identify.sol/IVerifier__factory";
export type { PlonkVerifier } from "./Verifier.sol/PlonkVerifier";
export { PlonkVerifier__factory } from "./factories/Verifier.sol/PlonkVerifier__factory";
