/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface IHasherInterface extends utils.Interface {
  functions: {
    "MiMCSponge(uint256,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "MiMCSponge"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MiMCSponge",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "MiMCSponge", data: BytesLike): Result;

  events: {};
}

export interface IHasher extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IHasherInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MiMCSponge(
      in_xL: BigNumberish,
      in_xR: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { xL: BigNumber; xR: BigNumber }>;
  };

  MiMCSponge(
    in_xL: BigNumberish,
    in_xR: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { xL: BigNumber; xR: BigNumber }>;

  callStatic: {
    MiMCSponge(
      in_xL: BigNumberish,
      in_xR: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { xL: BigNumber; xR: BigNumber }>;
  };

  filters: {};

  estimateGas: {
    MiMCSponge(
      in_xL: BigNumberish,
      in_xR: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MiMCSponge(
      in_xL: BigNumberish,
      in_xR: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
