/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IHasher,
  IHasherInterface,
} from "../../MerkleTreeWithHistory.sol/IHasher";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "in_xL",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "in_xR",
        type: "uint256",
      },
    ],
    name: "MiMCSponge",
    outputs: [
      {
        internalType: "uint256",
        name: "xL",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "xR",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class IHasher__factory {
  static readonly abi = _abi;
  static createInterface(): IHasherInterface {
    return new utils.Interface(_abi) as IHasherInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHasher {
    return new Contract(address, _abi, signerOrProvider) as IHasher;
  }
}
